# Generated by Django 4.1.7 on 2023-03-13 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='products',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='product',
            field=models.ForeignKey(default='Split Type', on_delete=django.db.models.deletion.CASCADE, to='JohnCarAirCo.productunit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
