# Generated by Django 4.1.7 on 2023-03-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircontype',
            old_name='airconType',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='customerdetails',
            old_name='customerAddress',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='customerdetails',
            old_name='customerContact',
            new_name='customer_contact',
        ),
        migrations.RenameField(
            model_name='customerdetails',
            old_name='customerEmail',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='customerdetails',
            old_name='customerName',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='productunit',
            old_name='unitName',
            new_name='unit_name',
        ),
        migrations.RenameField(
            model_name='productunit',
            old_name='unitPrice',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='productunit',
            old_name='unitStocks',
            new_name='unit_stock',
        ),
        migrations.RenameField(
            model_name='productunit',
            old_name='unitType',
            new_name='unit_type',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='dateOrdered',
            new_name='date_ordered',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='totalPrice',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='serviceorder',
            old_name='dateOrdered',
            new_name='date_ordered',
        ),
        migrations.RenameField(
            model_name='serviceorder',
            old_name='serviceDate',
            new_name='service_date',
        ),
        migrations.RenameField(
            model_name='serviceorder',
            old_name='totalPrice',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='servicetype',
            old_name='serviceCost',
            new_name='service_cost',
        ),
        migrations.RenameField(
            model_name='servicetype',
            old_name='serviceName',
            new_name='service_name',
        ),
        migrations.RenameField(
            model_name='techniciandetails',
            old_name='techEmail',
            new_name='tech_email',
        ),
        migrations.RenameField(
            model_name='techniciandetails',
            old_name='techName',
            new_name='tech_name',
        ),
        migrations.RenameField(
            model_name='techniciandetails',
            old_name='techPhone',
            new_name='tech_phone',
        ),
        migrations.RenameField(
            model_name='techniciandetails',
            old_name='techSched',
            new_name='tech_sched',
        ),
    ]
