# Generated by Django 4.1.7 on 2023-03-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0002_rename_aircontype_aircontype_type_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
