# Generated by Django 4.1.7 on 2023-03-27 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0003_alter_salesorder_total_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('cc_number', models.CharField(max_length=16)),
                ('cc_name', models.CharField(max_length=255)),
                ('cc_expiry', models.CharField(max_length=5)),
                ('cc_cvv', models.CharField(max_length=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JohnCarAirCo.serviceorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('cc_number', models.CharField(max_length=16)),
                ('cc_name', models.CharField(max_length=255)),
                ('cc_expiry', models.CharField(max_length=5)),
                ('cc_cvv', models.CharField(max_length=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JohnCarAirCo.salesorder')),
            ],
        ),
    ]
