# Generated by Django 4.1.7 on 2023-03-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0005_salesorderentry_entry_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderpayment',
            name='is_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceorderpayment',
            name='is_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesorderpayment',
            name='cc_cvv',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderpayment',
            name='cc_expiry',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderpayment',
            name='cc_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderpayment',
            name='cc_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorderpayment',
            name='cc_cvv',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorderpayment',
            name='cc_expiry',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorderpayment',
            name='cc_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorderpayment',
            name='cc_number',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
