# Generated by Django 4.1.7 on 2023-03-27 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0006_salesorderpayment_is_cash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JohnCarAirCo.customerdetails'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JohnCarAirCo.techniciandetails'),
        ),
    ]
