# Generated by Django 4.1.7 on 2023-02-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0009_rename_customer_id_salesorder_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='id',
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='serviceChoice',
            field=models.CharField(choices=[('Cars', 'Cars'), ('House', 'House'), ('Office', 'Office'), ('N/A', 'N/A')], default='N/A', max_length=50, primary_key=True, serialize=False),
        ),
    ]
