# Generated by Django 4.1.6 on 2023-02-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='estimatedCost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
