# Generated by Django 4.1.6 on 2023-02-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0002_alter_salesorder_totalprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='unitPrice',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
