# Generated by Django 4.1.6 on 2023-02-14 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0005_salesorder_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='unitOrdered',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JohnCarAirCo.salesorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JohnCarAirCo.productunit')),
            ],
        ),
        migrations.AddField(
            model_name='salesorder',
            name='products',
            field=models.ManyToManyField(through='JohnCarAirCo.OrderItem', to='JohnCarAirCo.productunit'),
        ),
    ]
