# Generated by Django 4.1.6 on 2023-02-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0006_remove_salesorder_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('deliveryDate', models.DateField()),
                ('itemDesc', models.CharField(max_length=255)),
                ('itemQuantity', models.PositiveIntegerField()),
                ('itemCost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JohnCarAirCo.customerdetails')),
                ('supplierName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JohnCarAirCo.supplierdetails')),
            ],
        ),
    ]
