# Generated by Django 4.1.7 on 2023-02-25 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0007_purchaseorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
