# Generated by Django 4.1.7 on 2023-03-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0010_remove_servicetype_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled')], default='Active', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled')], default='Active', max_length=255),
        ),
    ]
