# Generated by Django 4.1.7 on 2023-03-13 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0011_salesorder_status_serviceorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='technician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='JohnCarAirCo.techniciandetails'),
            preserve_default=False,
        ),
    ]
