# Generated by Django 4.1.7 on 2023-03-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0013_serviceorder_servicedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='totalPrice',
        ),
    ]
