# Generated by Django 4.1.7 on 2023-03-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JohnCarAirCo', '0014_remove_salesorder_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='unitType',
        ),
        migrations.AlterField(
            model_name='productunit',
            name='unitName',
            field=models.CharField(choices=[('Split Type', 'Split Type'), ('Window Air Conditioner', 'Window Air Conditioner'), ('N/A', 'N/A')], default='N/A', max_length=255, primary_key=True, serialize=False),
        ),
    ]
